name: Lint and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          git_no_verify: true
          eslint: true
          eslint_dir: src/
          eslint_extensions: ts,tsx
          eslint_args: '--max-warnings 0'
          prettier: true
          prettier_dir: src/
      - run: npm test
